module.exports = {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#002105",
        "on-primary-container": "#7c839b",
        "surface-container": "#eceef0",
        "surface-tint": "#565e74",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#04e54f",
        "secondary-fixed": "#6eff7c",
        outline: "#76777d",
        "on-surface": "#191c1e",
        "on-secondary-container": "#007122",
        "inverse-surface": "#2d3133",
        "on-background": "#191c1e",
        "inverse-on-surface": "#eff1f3",
        "on-primary-fixed": "#131b2e",
        "surface-container-highest": "#e0e3e5",
        "secondary-container": "#3dfd64",
        primary: "#000000",
        "on-surface-variant": "#45464d",
        "surface-container-high": "#e6e8ea",
        "primary-fixed": "#dae2fd",
        "surface-container-lowest": "#ffffff",
        error: "#ba1a1a",
        "surface-dim": "#d8dadc",
        "on-tertiary-fixed-variant": "#38485d",
        "outline-variant": "#c6c6cd",
        "surface-container-low": "#f2f4f6",
        "inverse-primary": "#bec6e0",
        "on-primary-fixed-variant": "#3f465c",
        "on-primary": "#ffffff",
        "primary-container": "#131b2e",
        "on-tertiary-container": "#75859d",
        "surface-bright": "#f7f9fb",
        "on-tertiary-fixed": "#0b1c30",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "tertiary-container": "#0b1c30",
        "on-secondary-fixed-variant": "#005317",
        "primary-fixed-dim": "#bec6e0",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#d3e4fe",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#b7c8e1",
        secondary: "#006e21",
        surface: "#f7f9fb",
        "surface-variant": "#e0e3e5",
        tertiary: "#000000",
        "on-secondary": "#ffffff",
        background: "#f7f9fb",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-lg": "24px",
        "container-max": "1440px",
        unit: "4px",
        "stack-xs": "4px",
        "margin-mobile": "16px",
        "stack-xl": "48px",
        "stack-md": "16px",
        "stack-sm": "8px",
        "margin-desktop": "40px",
        gutter: "24px",
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
        "display-lg": ["Inter"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
        headline: ["Inter"],
        display: ["Inter"],
        body: ["Inter"],
        label: ["Inter"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};
